# Generated by Django 3.2.5 on 2021-07-28 04:39

from django.db import migrations, models
import prs2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20190624_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment',
            field=models.FileField(max_length=255, storage=prs2.storage.PrsAzureStorage, upload_to='email_attachments/%Y/%m/%d'),
        ),
    ]
