# syntax=docker/dockerfile:1
# Args to centralise versions.
# NOTE: when updating the Typesense version, update the variable in `docker-bake.hcl` as well.
ARG TYPESENSE_VERSION=30.2
ARG UID=65532
ARG GID=65532

FROM typesense/typesense:${TYPESENSE_VERSION}
LABEL org.opencontainers.image.authors=asi@dbca.wa.gov.au \
  org.opencontainers.image.source=https://github.com/dbca-wa/typesense \
  org.opencontainers.image.description="Typesense"
# Arg scope: re-declare bare args inside the build stage.
ARG UID
ARG GID

# Create a nonroot user.
RUN groupadd -g ${GID} nonroot \
  && useradd --no-create-home --no-log-init --uid ${UID} --gid ${GID} nonroot

RUN chown -R nonroot:nonroot /opt/typesense-server
USER ${UID}
