# syntax=docker/dockerfile:1
# NOTE: when updating the Typesense base version, update the static tag in the GitHub workflow too.
FROM typesense/typesense:30.2
LABEL org.opencontainers.image.authors=asi@dbca.wa.gov.au
LABEL org.opencontainers.image.source=https://github.com/dbca-wa/typesense

# Create a non-root user.
ARG UID=10001
ARG GID=10001
RUN groupadd -g ${GID} typesense \
  && useradd --no-create-home --no-log-init --uid ${UID} --gid ${GID} typesense

RUN chown -R typesense:typesense /opt/typesense-server
USER ${UID}
