apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-typesense
spec:
  template:
    spec:
      containers:
        - name: prs-typesense
          envFrom:
            - secretRef:
                name: prs-env-uat
          volumeMounts:
            - mountPath: /data
              name: prs-typesense-data
      volumes:
        - name: prs-typesense-data
          persistentVolumeClaim:
            claimName: prs-typesense-data-uat
