# Generated by Django 3.2.5 on 2021-07-28 04:39

from django.db import migrations, models
import prs2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='filesize',
            field=models.IntegerField(blank=True, editable=False, help_text='Size of the uploaded file in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Allowed file types: TIF,JPG,GIF,PNG,DOC,DOCX,XLS,XLSX,CSV,PDF,TXT,ZIP,MSG,QGS,XML', max_length=255, null=True, storage=prs2.storage.PrsAzureStorage, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
